CREATE TABLE cart(
  id BINARY(16) NOT NULL DEFAULT UUID_TO_BIN(UUID()),
  dateCreated DATE,
  CONSTRAINT `PRIMARY` PRIMARY KEY(id)
);

CREATE TABLE cartItem(
  id BIGINT AUTO_INCREMENT NOT NULL,
  cart_id BINARY(16) NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY(id)
);

ALTER TABLE cartItem
     ADD CONSTRAINT cart_cartItem_fk FOREIGN KEY(cart_id) REFERENCES cart(id) ON DELETE CASCADE;